server:
  port: 8080
spring:
  application:
    #应用的名称
    name: take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    jedis:
      #redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms # 连接池最大阻塞等待时间
        max-idle: 4 #连接池中最大的空闲连接
        min-idle: 0 #连接池中最小的空闲连接
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
jpg:
  path: D:\jpg\
